<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PropertySeeder extends Seeder
{
    public function run()
    {
        $properties = [
            [
                'title' => 'Luxury Apartment in Abdoun',
                'slug' => 'luxury-apartment-abdoun',
                'description' => 'Modern apartment in the upscale Abdoun area, 3 bedrooms, 2 bathrooms, parking available',
                'property_type_id' => 1,
                'area_id' => 1,
                'user_id' => 1,
                'price' => 250000,
                'size' => 180,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floors' => 5,
                'year_built' => 2020,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => 'Abdoun, Al Madinah Al Munawarah Street',
                'latitude' => 31.956578,
                'longitude' => 35.945695,
                'parking_spaces' => 2,
                'is_featured' => true,
                'is_approved' => true,
                'views' => 150,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Villa for Rent in Sweifieh',
                'slug' => 'villa-for-rent-swefieh',
                'description' => 'Luxury villa in Sweifieh, 4 bedrooms, 3 bathrooms, private garden, large space',
                'property_type_id' => 2,
                'area_id' => 2,
                'user_id' => 2,
                'price' => 3500,
                'size' => 320,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'floors' => 2,
                'year_built' => 2018,
                'purpose' => 'rent',
                'status' => 'available',
                'address' => 'Sweifieh, Zahran Street',
                'latitude' => 31.969430,
                'longitude' => 35.875420,
                'parking_spaces' => 3,
                'is_featured' => true,
                'is_approved' => true,
                'views' => 230,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Land for Sale in Zarqa',
                'slug' => 'land-for-sale-zarqa',
                'description' => 'Residential land in Zarqa, prime location, 500 sqm, ready for immediate construction',
                'property_type_id' => 3,
                'area_id' => 3,
                'user_id' => 3,
                'price' => 80000,
                'size' => 500,
                'bedrooms' => null,
                'bathrooms' => null,
                'floors' => null,
                'year_built' => null,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => 'Zarqa, Maqsum District',
                'latitude' => 32.072753,
                'longitude' => 36.087643,
                'parking_spaces' => 0,
                'is_featured' => false,
                'is_approved' => true,
                'views' => 75,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Apartment for Sale in Jabal Amman',
                'slug' => 'apartment-for-sale-jabal-amman',
                'description' => 'Elegant apartment in Jabal Amman, 2 bedrooms, modern decor, great view',
                'property_type_id' => 1,
                'area_id' => 4,
                'user_id' => 4,
                'price' => 180000,
                'size' => 140,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'floors' => 3,
                'year_built' => 2015,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => 'Jabal Amman, Rainbow Street',
                'latitude' => 31.956120,
                'longitude' => 35.910540,
                'parking_spaces' => 1,
                'is_featured' => false,
                'is_approved' => true,
                'views' => 110,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Commercial Shop on University Street',
                'slug' => 'commercial-shop-university-street',
                'description' => 'Commercial shop in prime location on University Street, 60 sqm, suitable for various businesses',
                'property_type_id' => 4,
                'area_id' => 5,
                'user_id' => 5,
                'price' => 120000,
                'size' => 60,
                'bedrooms' => null,
                'bathrooms' => 1,
                'floors' => 1,
                'year_built' => 2010,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => 'University Street, opposite Arab Bank',
                'latitude' => 32.016450,
                'longitude' => 35.857840,
                'parking_spaces' => 0,
                'is_featured' => false,
                'is_approved' => true,
                'views' => 65,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Luxury Villa in Aqaba',
                'slug' => 'luxury-villa-aqaba',
                'description' => 'Luxury villa in Aqaba 5 minutes from the sea, 5 bedrooms, private pool, spacious garden',
                'property_type_id' => 2,
                'area_id' => 6,
                'user_id' => 6,
                'price' => 600000,
                'size' => 450,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'floors' => 2,
                'year_built' => 2019,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => 'Aqaba, Tala Bay Area',
                'latitude' => 29.558050,
                'longitude' => 34.995210,
                'parking_spaces' => 4,
                'is_featured' => true,
                'is_approved' => true,
                'views' => 320,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Furnished Apartment for Rent in Shmeisani',
                'slug' => 'furnished-apartment-rent-shmeisani',
                'description' => 'Fully furnished apartment in Shmeisani, 1 bedroom, air conditioned, full services',
                'property_type_id' => 1,
                'area_id' => 7,
                'user_id' => 7,
                'price' => 700,
                'size' => 90,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'floors' => 8,
                'year_built' => 2017,
                'purpose' => 'rent',
                'status' => 'available',
                'address' => 'Shmeisani, Makkah Street',
                'latitude' => 31.985670,
                'longitude' => 35.891230,
                'parking_spaces' => 1,
                'is_featured' => false,
                'is_approved' => true,
                'views' => 85,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Warehouse for Rent in Sahab',
                'slug' => 'warehouse-for-rent-sahab',
                'description' => 'Spacious warehouse in Sahab Industrial Area, 300 sqm, suitable for storage',
                'property_type_id' => 5,
                'area_id' => 8,
                'user_id' => 8,
                'price' => 1500,
                'size' => 300,
                'bedrooms' => null,
                'bathrooms' => 1,
                'floors' => 1,
                'year_built' => 2012,
                'purpose' => 'rent',
                'status' => 'available',
                'address' => 'Sahab, Industrial Area',
                'latitude' => 31.870940,
                'longitude' => 36.004560,
                'parking_spaces' => 2,
                'is_featured' => false,
                'is_approved' => true,
                'views' => 45,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Duplex Apartment in 7th Circle',
                'slug' => 'duplex-apartment-7th-circle',
                'description' => 'Elegant duplex apartment in 7th Circle, 3 bedrooms, modern decor, premium view',
                'property_type_id' => 6,
                'area_id' => 9,
                'user_id' => 9,
                'price' => 280000,
                'size' => 220,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floors' => 2,
                'year_built' => 2021,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => '7th Circle, Prince Hassan Street',
                'latitude' => 31.978890,
                'longitude' => 35.870120,
                'parking_spaces' => 2,
                'is_featured' => true,
                'is_approved' => true,
                'views' => 190,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Agricultural Land in Ramtha',
                'slug' => 'agricultural-land-ramtha',
                'description' => 'Fertile agricultural land in Ramtha, 5 dunums, water source available',
                'property_type_id' => 7,
                'area_id' => 10,
                'user_id' => 10,
                'price' => 60000,
                'size' => 5000,
                'bedrooms' => null,
                'bathrooms' => null,
                'floors' => null,
                'year_built' => null,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => 'Ramtha, Al Zuhour District',
                'latitude' => 32.558120,
                'longitude' => 36.008760,
                'parking_spaces' => 0,
                'is_featured' => false,
                'is_approved' => true,
                'views' => 55,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Residential Building in Marka',
                'slug' => 'residential-building-marka',
                'description' => 'New residential building in Marka, consists of 8 apartments, excellent investment income',
                'property_type_id' => 8,
                'area_id' => 11,
                'user_id' => 11,
                'price' => 750000,
                'size' => 800,
                'bedrooms' => 16,
                'bathrooms' => 8,
                'floors' => 4,
                'year_built' => 2022,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => 'Marka, Jordan Street',
                'latitude' => 32.028340,
                'longitude' => 35.931250,
                'parking_spaces' => 8,
                'is_featured' => true,
                'is_approved' => true,
                'views' => 280,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Studio Apartment in Jubeiha',
                'slug' => 'studio-apartment-jubeiha',
                'description' => 'Furnished studio apartment in Jubeiha, prime location near University of Jordan',
                'property_type_id' => 9,
                'area_id' => 12,
                'user_id' => 12,
                'price' => 550,
                'size' => 60,
                'bedrooms' => 0,
                'bathrooms' => 1,
                'floors' => 3,
                'year_built' => 2016,
                'purpose' => 'rent',
                'status' => 'available',
                'address' => 'Jubeiha, University of Jordan Street',
                'latitude' => 32.019560,
                'longitude' => 35.867890,
                'parking_spaces' => 0,
                'is_featured' => false,
                'is_approved' => true,
                'views' => 70,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Semi-Detached Villa in Rabieh',
                'slug' => 'semi-detached-villa-rabieh',
                'description' => 'Semi-detached villa in Rabieh, 3 bedrooms, front garden, quiet location',
                'property_type_id' => 10,
                'area_id' => 13,
                'user_id' => 13,
                'price' => 320000,
                'size' => 280,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floors' => 2,
                'year_built' => 2014,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => 'Rabieh, Al Kindi Street',
                'latitude' => 31.963780,
                'longitude' => 35.897340,
                'parking_spaces' => 2,
                'is_featured' => false,
                'is_approved' => true,
                'views' => 120,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Commercial Shop in Downtown',
                'slug' => 'commercial-shop-downtown',
                'description' => 'Commercial shop in downtown, prime location for various business projects',
                'property_type_id' => 4,
                'area_id' => 14,
                'user_id' => 14,
                'price' => 95000,
                'size' => 45,
                'bedrooms' => null,
                'bathrooms' => 1,
                'floors' => 1,
                'year_built' => 2008,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => 'Downtown, King Faisal Street',
                'latitude' => 31.951390,
                'longitude' => 35.932780,
                'parking_spaces' => 0,
                'is_featured' => false,
                'is_approved' => true,
                'views' => 60,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Apartment for Sale in Taborbour',
                'slug' => 'apartment-for-sale-tabarbour',
                'description' => 'New apartment in Taborbour, 2 bedrooms, simple decor, affordable price',
                'property_type_id' => 1,
                'area_id' => 15,
                'user_id' => 15,
                'price' => 85000,
                'size' => 110,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'floors' => 2,
                'year_built' => 2019,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => 'Taborbour, Al Nasr Street',
                'latitude' => 32.083450,
                'longitude' => 35.961230,
                'parking_spaces' => 1,
                'is_featured' => false,
                'is_approved' => true,
                'views' => 90,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Luxury Villa in Dabouq',
                'slug' => 'luxury-villa-dabouq',
                'description' => 'Luxury villa in Dabouq, 5 bedrooms, swimming pool, spacious garden, stunning view',
                'property_type_id' => 2,
                'area_id' => 16,
                'user_id' => 16,
                'price' => 850000,
                'size' => 500,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'floors' => 3,
                'year_built' => 2020,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => 'Dabouq, Al Arz Street',
                'latitude' => 32.012340,
                'longitude' => 35.843210,
                'parking_spaces' => 4,
                'is_featured' => true,
                'is_approved' => true,
                'views' => 350,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Apartment for Rent in Sports City',
                'slug' => 'apartment-for-rent-sports-city',
                'description' => 'Newly furnished apartment in Sports City, 1 bedroom, full services',
                'property_type_id' => 1,
                'area_id' => 17,
                'user_id' => 17,
                'price' => 650,
                'size' => 85,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'floors' => 6,
                'year_built' => 2018,
                'purpose' => 'rent',
                'status' => 'available',
                'address' => 'Sports City, Jordan Street',
                'latitude' => 31.992340,
                'longitude' => 35.876540,
                'parking_spaces' => 1,
                'is_featured' => false,
                'is_approved' => true,
                'views' => 80,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Residential Land in New Zarqa',
                'slug' => 'residential-land-new-zarqa',
                'description' => 'Residential land in New Zarqa, 700 sqm, prime location for construction',
                'property_type_id' => 3,
                'area_id' => 18,
                'user_id' => 18,
                'price' => 55000,
                'size' => 700,
                'bedrooms' => null,
                'bathrooms' => null,
                'floors' => null,
                'year_built' => null,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => 'New Zarqa, Al Rasheed District',
                'latitude' => 32.045670,
                'longitude' => 36.098760,
                'parking_spaces' => 0,
                'is_featured' => false,
                'is_approved' => true,
                'views' => 50,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Commercial Building in Shafa Badran',
                'slug' => 'commercial-building-shafa-badran',
                'description' => 'New commercial building in Shafa Badran, consists of 5 shops, excellent investment income',
                'property_type_id' => 11,
                'area_id' => 19,
                'user_id' => 19,
                'price' => 450000,
                'size' => 600,
                'bedrooms' => null,
                'bathrooms' => 5,
                'floors' => 3,
                'year_built' => 2021,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => 'Shafa Badran, Badran Street',
                'latitude' => 32.034560,
                'longitude' => 35.834320,
                'parking_spaces' => 5,
                'is_featured' => true,
                'is_approved' => true,
                'views' => 210,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ],
            [
                'title' => 'Apartment for Sale in Muqablein',
                'slug' => 'apartment-for-sale-muqablein',
                'description' => 'New apartment in Muqablein, 3 bedrooms, modern decor, affordable price',
                'property_type_id' => 1,
                'area_id' => 20,
                'user_id' => 20,
                'price' => 95000,
                'size' => 150,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'floors' => 4,
                'year_built' => 2017,
                'purpose' => 'sale',
                'status' => 'available',
                'address' => 'Muqablein, Queen Rania Street',
                'latitude' => 31.934560,
                'longitude' => 35.923450,
                'parking_spaces' => 1,
                'is_featured' => false,
                'is_approved' => true,
                'views' => 100,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ]
        ];

        DB::table('properties')->insert($properties);
    }
}
